apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres-cluster.yaml
  - secret.yaml
  - kratos-configmap.yaml
  - job-migrate.yaml
  - deployment.yaml
