apiVersion: v1
kind: Secret
metadata:
  name: kratos-dsn
  namespace: kratos
type: Opaque
stringData:
  DSN: "postgres://kratos:BBmK9SbQClrljxtB8TiUMAi2UR2qnX2cQKbLvJZvp9NzeSmLmitPFmaptCtA0fhk@postgres-kratos:5432/kratos?sslmode=require"
