apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-serviceaccount.yaml
  - 02-deployment.yaml
  - 03-service.yaml
  - 05-virtualservice.yaml
  - 06-destinationrule.yaml
